[Origin] SHOR-75
mobven/Shortly pull request #19
Opened 2023-01-12 08:24 UTC by mucahitbed

2023-01-12 09:16 UTC, AlparslanDevMobven requested changes

2023-01-12 09:16 UTC, AlparslanDevMobven commented on app/build.gradle
> +    implementation 'com.github.kenglxn.QRGen:android:3.0.1'
Android studio terminalini açıp şu komutu çalıştırır mısın
./gradlew refreshVersionsMigrate --mode=VersionsPropertiesOnly 
Dependency yönetimimiz bu yolla daha temiz olur.

2023-01-12 09:16 UTC, AlparslanDevMobven commented on app/src/main/java/com/mobven/shortly/ui/main/MainViewModel.kt
> +        val qrCode = QRCode.from(url).bitmap()
Bu objeye gerek var mı? direk return QRCode... desek çalışmaz mı

2023-01-12 11:31 UTC, AlparslanDevMobven commented on app/build.gradle
> +    implementation 'com.github.kenglxn.QRGen:android:3.0.1'
Resolve etmişiz ancak bu düzelmemiş. Bu kullanım standarta uymuyor dediğim gibi komutu çalıştırıp sync yapıp değişiklikleri commit atar mısın?

2023-01-12 11:54 UTC, rkonuk commented on app/src/main/java/com/mobven/shortly/ui/main/MainViewModel.kt
> +    fun createQrCode(url: String): Bitmap {
Single expression fonks. olarak yazabiliriz.

2023-01-12 15:20 UTC, abalta-mobven commented on app/src/main/java/com/mobven/shortly/ui/list/MyLinksFragment.kt
> +        val dialogBuilder = Dialog(requireContext())
Material dialog kullanalım.

2023-01-12 15:20 UTC, abalta-mobven commented on app/src/main/java/com/mobven/shortly/ui/list/MyLinksFragment.kt
> +            var imgQrCode = findViewById<ImageView>(R.id.img_qr_code)
findViewById yerin binding kullanalım

2023-01-12 15:21 UTC, abalta-mobven commented on app/src/main/res/layout/popup_dialog_qr.xml
> +    <ImageView
LinearLayout gereksiz duruyor.

2023-01-12 15:22 UTC, abalta-mobven reviewed
Yorumlarımı girdim.

2023-03-03 13:57 UTC, mucahitbed commented on app/src/main/java/com/mobven/shortly/ui/list/MyLinksFragment.kt
> +        val dialogBuilder = Dialog(requireContext())
Material dialog kullandığımda setContentView() kullanamıyorum

2023-03-08 12:47 UTC, abalta-mobven approved these changes

2023-03-08 12:47 UTC, merged