SHOR-72-Firebase crashlytics implementation
mobven/Shortly pull request #20
Opened 2023-01-12 11:09 UTC by tugfeivecek-mobven

2023-01-12 11:23 UTC, abalta-mobven requested changes
Yorumlarımı ekledim.

2023-01-12 11:23 UTC, abalta-mobven commented on app/build.gradle
> +    id 'com.google.firebase.crashlytics'
Bu şekilde eklediğimizde geliştirme yaparken karşılaştığımız crashler de Firebase'e düşücek. Debug build'de düşmemesi lazım.

2023-01-12 11:23 UTC, abalta-mobven commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:3.4.0'
Burdaki bağımlılıkların eklenmesinde standarda uyulmamış.

2023-01-12 13:10 UTC, AlparslanDevMobven approved these changes

2023-01-12 13:46 UTC, AlparslanDevMobven approved these changes

2023-01-12 15:26 UTC, abalta-mobven commented on app/build.gradle
> +            manifestPlaceholders["crashlytics_enabled"] = "true"
Firebase mapping upload parametresi de eklenmesi gerekiyor.

2023-01-12 15:26 UTC, abalta-mobven reviewed
Yorumladım.

2023-01-24 10:32 UTC, abalta-mobven approved these changes

2023-01-24 10:32 UTC, merged